### PR TITLE
Add poly, demigirl, demiboy, and agender

### PR DESCRIPTION
**Pull request by lond-en**
I added poly, demigirl, demiboy, and agender! This is my first pull request and I'm agender so I'm excited, but I understand if you reject the PR :D!

### CODE REVIEW

**Comment by lond-en** [comment]
Wait I forgot to edit the help information I'm an idiot

**Comment by lond-en** [comment]
oh wait it does that automatically im a real big idiot

**Comment by ms-jpq** [comment]
ohhhh thank you this is very cool!

good job on your first PR!

Im gonna merge this in later today and do a release when i come back from the doctor, he's gonna do some ouchies on me :<

**Comment by lond-en** [comment]
Thank you! I'll probably do more since you like it!

**Comment by ms-jpq** [comment]
I did a release now you can do

```sh
pip3 install -U gay
```

to get the latest gay <3

**Pull request merged**
